os: linux
dist: bionic
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.mvn/
script: mvn package
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: "target/EliteMobs*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true