os: linux
dist: bionic
language: java
jdk:
  - openjdk8
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: "build/libs/EliteMobs*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true