package com.magmaguy.elitemobs.items;

import com.magmaguy.elitemobs.MetadataHandler;
import com.magmaguy.elitemobs.api.utils.EliteItemManager;
import com.magmaguy.elitemobs.config.ItemSettingsConfig;
import com.magmaguy.elitemobs.config.enchantments.premade.SoulbindConfig;
import com.magmaguy.elitemobs.items.customenchantments.SoulbindEnchantment;
import com.magmaguy.elitemobs.utils.CustomModelAdder;
import com.magmaguy.magmacore.util.ChatColorConverter;
import com.magmaguy.magmacore.util.ItemStackGenerator;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class EliteScroll {
    public static final NamespacedKey eliteScrollNamespacedKey = new NamespacedKey(MetadataHandler.PLUGIN, "elite_scroll");
    public static Material scrollMaterial = Material.PAPER;

    private EliteScroll() {
    }

    public static ItemStack generateScroll(int scrollLevel, Player player) {
        // Generate base item
        ItemStack itemStack = ItemStackGenerator.generateItemStack(scrollMaterial, ItemSettingsConfig.getEliteItemScrollName());

        // Get meta once and reuse
        ItemMeta itemMeta = itemStack.getItemMeta();
        if (itemMeta == null) return itemStack; // Safety check

        // Set persistent data
        itemMeta.getPersistentDataContainer().set(eliteScrollNamespacedKey, PersistentDataType.INTEGER, scrollLevel);

        // Add custom model
        CustomModelAdder.addCustomModel(itemMeta, ItemSettingsConfig.getEliteItemModel());

        itemStack.setItemMeta(itemMeta);

        // Register and add enchantments after meta is set
        ItemTagger.registerEliteItem(itemStack);
        SoulbindEnchantment.addEnchantment(itemStack, player);

        itemMeta = itemStack.getItemMeta();

        // Build scroll-specific lore only (don't keep elite item lore generated by registerEliteItem/addEnchantment
        // since scrolls have no elite level and it would show level 0 / prestige 0)
        List<String> lore = new ArrayList<>();
        for (String line : ItemSettingsConfig.getEliteItemScrollLore()) {
            lore.add(ChatColorConverter.convert(line.replace("$level", String.valueOf(scrollLevel))));
        }
        // The static config lore above replaces the soulbound line generated by addEnchantment, so re-add it
        // when the scroll is actually soulbound to a player.
        if (player != null && SoulbindEnchantment.itemHasSoulbindEnchantment(itemMeta))
            lore.add(ChatColorConverter.convert(SoulbindConfig.loreStrings
                    .replace("$player", player.getDisplayName())
                    .replace("$playerName", player.getName())));
        itemMeta.setLore(lore);

        // Apply meta changes once
        itemStack.setItemMeta(itemMeta);

        return itemStack;
    }

    public static boolean isEliteScroll(ItemStack itemStack) {
        if (itemStack == null) return false;
        if (!itemStack.hasItemMeta()) return false;
        return itemStack.getItemMeta().getPersistentDataContainer().has(eliteScrollNamespacedKey, PersistentDataType.INTEGER);
    }

    public static int getEliteScrollLevel(ItemStack itemStack) {
        if (!isEliteScroll(itemStack)) return 0;
        return itemStack.getItemMeta().getPersistentDataContainer().get(eliteScrollNamespacedKey, PersistentDataType.INTEGER);
    }

    /**
     * A bound scroll can only be spent by its stored owner. Check the UUID directly so
     * offline owners and soulbind bypass permissions cannot authorize someone else's scroll.
     * Scrolls without an owner remain usable by anyone.
     */
    public static boolean canUseScroll(Player player, ItemStack scrollItemStack) {
        if (player == null || !isEliteScroll(scrollItemStack) || scrollItemStack.getAmount() <= 0) return false;
        var data = scrollItemStack.getItemMeta().getPersistentDataContainer();
        if (!data.has(SoulbindEnchantment.SOULBIND_KEY)) return true;
        return data.has(SoulbindEnchantment.SOULBIND_KEY, PersistentDataType.STRING)
                && player.getUniqueId().toString().equals(data.get(SoulbindEnchantment.SOULBIND_KEY, PersistentDataType.STRING));
    }

    /**
     * Returns a converted copy, or null when the player cannot use these inputs.
     * Soulbind ownership and prestige belong to the original item, never to the scroll.
     */
    public static ItemStack convertVanillaItem(ItemStack originalItem, ItemStack scrollItemStack, Player player) {
        if (!canUseScroll(player, scrollItemStack) || originalItem == null
                || originalItem.getType().isAir() || originalItem.getAmount() <= 0
                || EliteItemManager.isEliteMobsItem(originalItem)) return null;
        ItemStack newItem = originalItem.clone();
        int level = getEliteScrollLevel(scrollItemStack);

        // Set elite level, damage/defense
        EliteItemManager.setEliteLevel(newItem, level);

        ItemMeta itemMeta = newItem.getItemMeta();
        if (itemMeta == null) return newItem;

        // Hide vanilla enchantment tooltips — elite lore displays them instead
        if (ItemSettingsConfig.isHideEnchants())
            itemMeta.addItemFlags(ItemFlag.HIDE_ENCHANTS);

        // Register the item's vanilla enchantments into PDC for the EM 10 combat system
        HashMap<Enchantment, Integer> enchantmentMap = new HashMap<>(itemMeta.getEnchants());
        ItemTagger.registerEnchantments(itemMeta, enchantmentMap);

        // Register item source
        ItemTagger.registerItemSource(null, itemMeta);

        newItem.setItemMeta(itemMeta);

        // Generate lore once with all data ready
        new EliteItemLore(newItem, false);

        return newItem;
    }
}
