name: EliteMobs
version: 7.0.17
author: MagmaGuy
main: com.magmaguy.elitemobs.EliteMobs
api-version: 1.13
softdepend: [Multiverse-Core, WorldGuard, Vault]

commands:
  elitemobs:
    description: Catch-all command
    usage: /elitemobs
    aliases: [em, adventurerguild, adventurersguild, ag, shareitem]
permissions:
  elitemobs.*:
    description: Gives access to all elitemobs commands
    children:
      elitemobs.stats: true
      elitemobs.shop: true
      elitemobs.getloot: true
      elitemobs.simloot: true
      elitemobs.reload.configs: true
      elitemobs.reload.loot: true
      elitemobs.giveloot: true
      elitemobs.spawnmob: true
      elitemobs.killall.aggressiveelites: true
      elitemobs.killall.passiveelites: true
      elitemobs.killall.specificentity: true
      elitemobs.currency.user: true
      elitemobs.currency.subtract: true
      elitemobs.currency.set: true
      elitemobs.currency.check: true
      elitemobs.currency.add: true
      elitemobs.currency.cointop: true
      elitemobs.scoreboard: false
      elitemobs.events.*: true
    default: op
  elitemobs.currency.user:
    description: Gives access to the commands users need to use the economy features (shops, paying other players)
    children:
      elitemobs.shop: true
      elitemobs.customshop: true
      elitemobs.currency.pay: true
      elitemobs.currency.wallet: true
      elitemobs.currency.cointop: true
  elitemobs.killall.*:
      description: Allows players to run all /elitemobs kill variations
      children:
        elitemobs.killall.aggressiveelites: true
        elitemobs.killall.passiveelites: true
        elitemobs.killall.specificentity: true
  elitemobs.user:
      description: Gives access to all recommended user commands
      children:
        elitemobs.stats: true
        elitemobs.events.kraken: true
        elitemobs.events.balrog: true
        elitemobs.events.fae: true
        elitemobs.checktier: true
        elitemobs.adventurersguild: true
        elitemobs.currency.user: true
  elitemobs.stats:
    description: Allows players to run /elitemobs stats
    default: op
  elitemobs.version:
    description: Allows players to run /elitemobs version
    default: true
  elitemobs.getloot:
    description: Allow players to run /elitemobs getloot
    default: op
  elitemobs.simloot:
    description: Allow players to run /elitemobs simloot
    default: op
  elitemobs.reload:
    decription: Allow players to run /elitemobs reload config
    default: op
  elitemobs.giveloot:
    description: Allow players to run /elitemobs giveloot [playername] random/[loot name]
    default: op
  elitemobs.spawnmob:
    description: Allow players to run /elitemobs SpawnMob [mobType] [mobLevel] [mobPower] [mobPower(just keep adding until done)]
    default: op
  elitemobs.spawnbossmob:
    description: Allows players to run /elitemobs spawnbossmob [bossmob]
    default: op
  elitemobs.scoreboard:
    description: Shows a scoreboard with info about the elite mob a player might be standing next to
    default: false
  elitemobs.killall.aggressiveelites:
    description: Allows players to run /elitemobs kill aggressive
    default: op
  elitemobs.killall.passiveelites:
    description: Allows players to run /elitemobs kill passive
    default: op
  elitemobs.killall.specificentity:
    description: Allows players to run /elitemobs kill [entityType]
    default: op
  elitemobs.shop:
    description: Allows players to run /elitemobs shop and interact with npcs
    children:
      elitemobs.shop.npc: true
      elitemobs.shop.command: true
    default: op
  elitemobs.shop.npc:
    description: Allows players to interact with NPCs for dynamic shops
    default: op
  elitemobs.shop.command:
    description: Allows players to open the dynamic shop menu through commands
    default: op
  elitemobs.customshop:
    decription: Allows players to run /elitemobs customshop
    children:
      elitemobs.customshop.npc: true
      elitemobs.customshop.command: true
    default: op
  elitemobs.customshop.npc:
    description: Allows players to interact with NPCs for dynamic shops
    default: op
  elitemobs.customshop.command:
    description: Allows players to open the dynamic shop menu through commands
    default: op
  elitemobs.currency.pay:
    description: Allows players to run /elitemobs pay [username] [amount]
    default: op
  elitemobs.currency.add:
    description: Allows players to run /elitemobs add [username] [amount]
    default: op
  elitemobs.currency.subtract:
    description: Allows players to run /elitemobs subtract [username] [amount]
    default: op
  elitemobs.currency.set:
    description: Allows players to run /elitemobs set [username] [amount]
    default: op
  elitemobs.currency.check:
    description: Allows players to run /elitemobs check [username]
    default: op
  elitemobs.currency.wallet:
    description: Allows players to run /elitemobs wallet
    default: op
  elitemobs.currency.cointop:
    description: Allows players to run /elitemobs highscore
    default: op
  elitemobs.events.*:
    description: Allows players to launch all events
    children:
      elitemobs.events.smalltreasuregoblin: true
      elitemobs.events.deadmoon: true
    default: op
  elitemobs.events.smalltreasuregoblin:
    description: Allows players to run /elitemobs event smalltreasuregoblin
    default: op
  elitemobs.events.deadmoon:
    description: Allows players to run /elitemobs event deadmoon
    default: op
  elitemobs.events.kraken:
    description: Allows players to randomly trigger the Kraken event when fishing;
    defaut: true
  elitemobs.events.balrog:
    description: Allows players to randomly trigger the Balrog event when mining ore veins
    default: true
  elitemobs.events.fae:
    description: Allows players to randomly trigger the Fae event when chopping down trees
    default: true
  elitemobs.config.setmaxtier:
    description: Allows players to run /elitemobs setmaxtier [tier]
    default: op
  elitemobs.checktier:
    description: Allows players to run /elitemobs checktier
    default: op
  elitemobs.checkmaxtier:
    description: Allows players to run /elitemobs checkmaxtier
    default: op
  elitemobs.gettier:
    description: Allows players tu run /elitemobs gettier [tier]
    default: op
  elitemobs.versionnotification:
    description: Allows players to get notified about plugin updates
    default: op
  elitemobs.adventurersguild:
    description: Allows players to use the /ag command to set their difficulty level and get quests
    children:
      elitemobs.adventurersguild.teleport: true
      elitemobs.adventurersguild.menu: true
    default: op
  elitemobs.adventurersguild.teleport:
    description: Allows players to teleport to the adventurer's guild hub using /ag
    default: op
  elitemobs.adventurersguild.menu:
    description: Allows players to open the adventurer's guild menu through /ag
    default: op
  elitemobs.npc.set:
    description: Allows players to set the location of a specific NPC
    default: op
  elitemobs.npc.remove:
    description: Allows players to remove a specific NPC
    default: op
  elitemobs.npc.add:
    description: Allows players to add a specific NPC
    default: op
  elitemobs.autosetup:
    description: Allows players to run /em autosetup. This is used for setting up the adventurer's guild map
    default: op