package com.magmaguy.elitemobs.config;

import com.magmaguy.elitemobs.items.itemconstructor.MaterialGenerator;
import lombok.Getter;
import org.bukkit.Material;
import org.bukkit.configuration.file.FileConfiguration;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ProceduralItemGenerationSettingsConfig {
    @Getter
    private static final List<String> validMaterials = new ArrayList<>();
    @Getter
    private static FileConfiguration fileConfiguration;
    @Getter
    private
    static boolean doProceduralItemDrops;
    @Getter
    private static double customEnchantmentChance;
    @Getter
    private static String swordName;
    @Getter
    private static String bowName;
    @Getter
    private static String pickaxeName;
    @Getter
    private static String spadeName;
    @Getter
    private static String hoeName;
    @Getter
    private static String axeName;
    @Getter
    private static String helmetName;
    @Getter
    private static String chestplateName;
    @Getter
    private static String leggingsName;
    @Getter
    private static String bootsName;
    @Getter
    private static String shearsName;
    @Getter
    private static String fishingRodName;
    @Getter
    private static String shieldName;
    @Getter
    private static String tridentName;
    @Getter
    private static String crossbowName;
    @Getter
    private static List<String> nameFormat;
    @Getter
    private static List<String> nouns;
    @Getter
    private static List<String> adjectives;
    @Getter
    private static List<String> verbs;
    @Getter
    private static List<String> verbers;

    private ProceduralItemGenerationSettingsConfig() {
    }

    public static void initializeConfig() {
        File file = ConfigurationEngine.fileCreator("ProceduralItemGenerationSettings.yml");
        fileConfiguration = ConfigurationEngine.fileConfigurationCreator(file);

        doProceduralItemDrops = ConfigurationEngine.setBoolean(fileConfiguration, "dropProcedurallyGeneratedItems", true);
        customEnchantmentChance = ConfigurationEngine.setDouble(fileConfiguration, "customEnchantmentsChance", 0.5);

        addMaterial(Material.DIAMOND_HELMET);
        addMaterial(Material.DIAMOND_CHESTPLATE);
        addMaterial(Material.DIAMOND_LEGGINGS);
        addMaterial(Material.DIAMOND_BOOTS);

        addMaterial(Material.DIAMOND_SWORD);
        addMaterial(Material.DIAMOND_AXE);


        addMaterial(Material.IRON_HELMET);
        addMaterial(Material.IRON_CHESTPLATE);
        addMaterial(Material.IRON_LEGGINGS);
        addMaterial(Material.IRON_BOOTS);

        addMaterial(Material.IRON_SWORD);
        addMaterial(Material.IRON_AXE);


        addMaterial(Material.GOLDEN_HELMET);
        addMaterial(Material.GOLDEN_CHESTPLATE);
        addMaterial(Material.GOLDEN_LEGGINGS);
        addMaterial(Material.GOLDEN_BOOTS);

        addMaterial(Material.GOLDEN_SWORD);
        addMaterial(Material.GOLDEN_AXE);


        addMaterial(Material.CHAINMAIL_HELMET);
        addMaterial(Material.CHAINMAIL_CHESTPLATE);
        addMaterial(Material.CHAINMAIL_LEGGINGS);
        addMaterial(Material.CHAINMAIL_BOOTS);


        addMaterial(Material.LEATHER_HELMET);
        addMaterial(Material.LEATHER_CHESTPLATE);
        addMaterial(Material.LEATHER_LEGGINGS);
        addMaterial(Material.LEATHER_BOOTS);


        addMaterial(Material.STONE_SWORD);
        addMaterial(Material.STONE_AXE);


        addMaterial(Material.WOODEN_SWORD);
        addMaterial(Material.WOODEN_AXE);


        addMaterial(Material.SHIELD);
        addMaterial(Material.TURTLE_HELMET);
        addMaterial(Material.TRIDENT);
        addMaterial(Material.BOW);
        addMaterial(Material.CROSSBOW);

        cacheMaterials();

        swordName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.swordName", "Sword", true);
        bowName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.bowName", "Bow", true);
        pickaxeName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.pickaxe", "Pickaxe", true);
        spadeName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.spade", "Spade", true);
        hoeName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.hoe", "Hoe", true);
        axeName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.axe", "Axe", true);
        helmetName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.helmet", "Helmet", true);
        chestplateName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.chestplate", "Chestplate", true);
        leggingsName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.leggings", "Leggings", true);
        bootsName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.boots", "Boots", true);
        shearsName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.shears", "Shears", true);
        fishingRodName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.fishingRod", "Fishing Rod", true);
        shieldName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.shield", "Shield", true);
        tridentName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.trident", "Trident", true);
        crossbowName = ConfigurationEngine.setString(file, fileConfiguration, "materialNames.crossbow", "Crossbow", true);

        nameFormat = ConfigurationEngine.setList(file, fileConfiguration, "nameFormats", Arrays.asList(
                "$verb $itemType of the $adjective $noun",
                "$itemType of the $adjective $noun",
                "$noun's $adjective $verb $itemType",
                "$verb $itemType",
                "$adjective $verb $itemType",
                "The $verb-er",
                "The $adjective $verb-er"
        ), true);

        nouns = ConfigurationEngine.setList(file, fileConfiguration, "nouns", Arrays.asList(
                "MagmaGuy",
                "Dawn",
                "Sunset",
                "Heaven",
                "Hell",
                "Angel",
                "Archangel",
                "Cherub",
                "Seraph",
                "Demon",
                "Fiend",
                "Bat",
                "Chicken",
                "Cow",
                "Mooshroom",
                "Pig",
                "Rabbit",
                "Sheep",
                "Squid",
                "Villager",
                "Cave Spider",
                "Enderman",
                "Polar Bear",
                "Spider",
                "Zombie Pigman",
                "Blaze",
                "Creeper",
                "Elder Guardian",
                "Endermite",
                "Evoker",
                "Ghast",
                "Guardian",
                "Husk",
                "Magma Cube",
                "Shulker",
                "Silverfish",
                "Skeleton",
                "Slime",
                "Stray",
                "Vex",
                "Vindicator",
                "Witch",
                "Wither Skeleton",
                "Zombie",
                "Donkey",
                "Horse",
                "Llama",
                "Mule",
                "Ocelot",
                "Wolf",
                "Iron Golem",
                "Snow Golem",
                "Ender Dragon",
                "Wither",
                "Illusioner",
                "Parrot",
                "Giant",
                "Killer Bunny",
                "Steve",
                "Wolfbane",
                "Chaos",
                "Aeon",
                "Dragon",
                "Sphynx",
                "Minotaur",
                "Hades",
                "Oath",
                "Oathbreaker",
                "Deserter",
                "Betrayer",
                "Jade",
                "Light",
                "Darkness",
                "Oblivion",
                "Shadow",
                "Void",
                "Xeno",
                "Zealot",
                "Zenith",
                "Dusk",
                "Twilight",
                "Mob",
                "Elite  Mob",
                "Urist",
                "Dwarf",
                "Elf",
                "Ork",
                "Goblin",
                "Gnome",
                "Goliath",
                "Drow",
                "Human",
                "Halfling",
                "Half-Orc",
                "Beholder",
                "Mind Flayer",
                "Owlbear",
                "Bulette",
                "Rust Monster",
                "Hill Giant",
                "Stone Giant",
                "Frost Giant",
                "Fire Giant",
                "Cloud Giant",
                "Storm Giant",
                "Kobold",
                "Lich",
                "Ork",
                "Umber Hulk",
                "Fighter",
                "Wizard",
                "Paladin",
                "Cleric",
                "Ranger",
                "Archer",
                "Mage",
                "Tiefling",
                "Werewolf",
                "Vampire",
                "Centaur",
                "Catfolk",
                "Half-Giant",
                "Ogre",
                "Troll",
                "Rogue",
                "Barbarian",
                "Bard",
                "Druid",
                "Monk",
                "Sorcerer",
                "Warlock",
                "Demon Hunter",
                "Death Knight",
                "Priest",
                "Shaman",
                "Warrior",
                "Basilisk",
                "Chimera",
                "Imp",
                "Dryad",
                "Gargoyle",
                "Djinni",
                "Efreeti",
                "Ghost",
                "Hobgoblin",
                "Hydra",
                "Kraken",
                "Lamia",
                "Medusa",
                "Mimic",
                "Mummy",
                "Pegasus",
                "Roc",
                "Satyr",
                "Tarrasque",
                "Abomination",
                "Ghoul",
                "Treant",
                "Unicorn",
                "Wraith",
                "Acolyte",
                "Gladiator",
                "Knight",
                "Gryphon",
                "Raider",
                "Scout",
                "Spy",
                "Thg",
                "Noble",
                "Guard",
                "Veteran",
                "Wyvern",
                "Abyssal",
                "Infernal",
                "Elemental",
                "Tauren",
                "Pandaren",
                "Sasquatch",
                "Forsaken",
                "Yeti",
                "Banshee",
                "Arachnid",
                "Undead",
                "Night Elf",
                "Blood Elf",
                "Draenei",
                "Worgen",
                "Warlord",
                "Witch",
                "Magi",
                "Sage",
                "Thief",
                "Assassin",
                "Templar",
                "Beastmaster",
                "Berserker",
                "Inventor",
                "Luchador",
                "Pirate",
                "Vanguard",
                "Voidblade",
                "Wisp",
                "Peasant",
                "Footman",
                "Swordsman",
                "Thrall",
                "Felhound",
                "Huntress",
                "Hunter",
                "Aarakorcra",
                "Aboleth",
                "Deva",
                "Planetar",
                "Solar",
                "Ankheg",
                "Azer",
                "Behir",
                "Death Tyrant",
                "Blight",
                "Bugbear",
                "Hugbear",
                "Bullywug",
                "Cambion",
                "Chuul",
                "Lich King",
                "Cockatrice",
                "Couatl",
                "Cyclops",
                "Titan",
                "Darkmantle",
                "Ancient One",
                "Demilich",
                "Balor",
                "Barlgura",
                "Chasme",
                "Dretch",
                "Glabrezu",
                "Goristro",
                "Hezrou",
                "Manes",
                "Marilith",
                "Nalfeshnee",
                "Quasit",
                "Vrock",
                "Yochlol",
                "Pit Fiend",
                "Lemure",
                "Dracolich",
                "Doppleganger",
                "Chromatic Dragon",
                "Drider",
                "Air Elemental",
                "Earth Elemental",
                "Fire Elemental",
                "Water Elemental",
                "Rohirrim",
                "Gondorian",
                "Empyrean",
                "Faerie Dragon",
                "Ettin",
                "Flumph",
                "Fomorian",
                "Dao",
                "Gnoll",
                "Parshendi",
                "Listener",
                "Spren",
                "Stormfather",
                "Rosharian",
                "Brightlord",
                "Highprince",
                "King",
                "Emperor",
                "Shardbearer",
                "Surgebinder",
                "Bondsmith",
                "Golem",
                "Gorgon",
                "Hag",
                "Harpy",
                "Hippogriff",
                "Homunculus",
                "State Alchemist",
                "Undying Soldier",
                "Jackalwere",
                "Nothic",
                "Oni",
                "Rakshasa",
                "Revenant",
                "Cultist"
        ), true);

        adjectives = ConfigurationEngine.setList(file, fileConfiguration, "adjectives", Arrays.asList(
                "Adorable",
                "Beautiful",
                "Clean",
                "Elegant",
                "Fancy",
                "Glamorous",
                "Handsome",
                "Long",
                "Magnificent",
                "Plain",
                "Quaint",
                "Sparkling",
                "Ugliest",
                "Red",
                "Orange",
                "Yellow",
                "Green",
                "Blue",
                "Purple",
                "Gray",
                "Black",
                "White",
                "Dead",
                "Odd",
                "Powerful",
                "Rich",
                "Vast",
                "Zealous",
                "Deafening",
                "Faint",
                "Melodic",
                "Quiet",
                "Thundering",
                "Whispering",
                "Hissing",
                "Ancient",
                "Fast",
                "Old",
                "Rapid",
                "Slow",
                "Rotten",
                "Creepy",
                "Crooked",
                "Empty",
                "Heavy",
                "Abhorrent",
                "Abnormal",
                "Absurd",
                "Acceptable",
                "Accidental",
                "Adamant",
                "Adventurous",
                "Agonizing",
                "Alert",
                "Annoyed",
                "Annoying",
                "Anxious",
                "Aromatic",
                "Aggressive",
                "Aloof",
                "Amazing",
                "Ambiguous",
                "Ambitious",
                "Amused",
                "Angry",
                "Arrogant",
                "Ashamed",
                "Aspiring",
                "Astonishing",
                "Auspicious",
                "Average",
                "Awesome",
                "Awful",
                "Bad",
                "Barbarous",
                "Bashful",
                "Beffiting",
                "Belligerent",
                "Beneficial",
                "Berserk",
                "Best",
                "Bewildered",
                "Big",
                "Bitter",
                "Bizarre",
                "Bloody",
                "Boiling",
                "Boundless",
                "Brash",
                "Brave",
                "Brawny",
                "Breakable",
                "Brief",
                "Bright",
                "Broken",
                "Busy",
                "Calculating",
                "Callous",
                "Calm",
                "Capricious",
                "Careful",
                "Careless",
                "Caring",
                "Cautious",
                "Ceaseless",
                "Certain",
                "Charming",
                "Cheap",
                "Chief",
                "Chilly",
                "Chivalrous",
                "Chunky",
                "Clear",
                "Clever",
                "Cloistered",
                "Clumsy",
                "Cloudy",
                "Classy",
                "Colossal",
                "Combative",
                "Common",
                "Confused",
                "Condemned",
                "Cool",
                "Courageous",
                "Cowardly",
                "Crazy",
                "Craven",
                "Cruel",
                "Cuddly",
                "Curious",
                "Cute",
                "Damaged",
                "Damaging",
                "Dangerous",
                "Dark",
                "Dashing",
                "Decisive",
                "Deep",
                "Defeated",
                "Defective",
                "Defiant",
                "Delicate",
                "Delicious",
                "Delightful",
                "Demonic",
                "Delirious",
                "Deranged",
                "Descriptive",
                "Devilish",
                "Difficult",
                "Diligent",
                "Direful",
                "Dirty",
                "Disastrous",
                "Disgusted",
                "Disgusting",
                "Disillusioned",
                "Distinct",
                "Disturbed",
                "Draconian",
                "Dramatic",
                "Dreary",
                "Dysfunctional",
                "Eager",
                "Elderly",
                "Electric",
                "Elite",
                "Enchanted",
                "Enchanting",
                "Energetic",
                "Enormous",
                "Entertaining",
                "Enthusiastic",
                "Envious",
                "Erratic",
                "Ethereal",
                "Evasive",
                "Excellent",
                "Excited",
                "Exciting",
                "Exotic",
                "Exuberant",
                "Fabulous",
                "Faded",
                "Fair",
                "Faithful",
                "False",
                "Familiar",
                "Famous",
                "Fanatical",
                "Fantastic",
                "Fascinated",
                "Fat",
                "Fearful",
                "Fearless",
                "Feeble",
                "Festive",
                "Fierce",
                "Filthy",
                "Fine",
                "Finicky",
                "First",
                "Fixed",
                "Flashy",
                "Flawless",
                "Flimsy",
                "Flippant",
                "Flowery",
                "Fluffy",
                "Fluttering",
                "Foamy",
                "Foolish",
                "Forgetful",
                "Fortunate",
                "Frail",
                "Fragile",
                "Frantic",
                "Free",
                "Freezing",
                "Fresh",
                "Friendly",
                "Frightening",
                "Fumbling",
                "Funny",
                "Furry",
                "Furtive",
                "Fuzzy",
                "Giant",
                "Gifted",
                "Gigantic",
                "Glistening",
                "Glorious",
                "Godly",
                "Good",
                "Goofy",
                "Gorgeous",
                "Graceful",
                "Grandiose",
                "Grateful",
                "Greasy",
                "Great",
                "Greedy",
                "Grieving",
                "Groovy",
                "Grotesque",
                "Grubby",
                "Gruesome",
                "Grumpy",
                "Guarded",
                "Guiltless",
                "Gullible",
                "Gutsy",
                "Guttural",
                "Hallowed",
                "Hanging",
                "Hapless",
                "Happy",
                "Harmonious",
                "Hateful",
                "Healthy",
                "Heartbreaking",
                "Heavenly",
                "Hellish",
                "Helpful",
                "Helpless",
                "Hesitant",
                "Hideous",
                "Hilarious",
                "Hollow",
                "Homeless",
                "Honorable",
                "Horrible",
                "Hospitable",
                "Huge",
                "Hulking",
                "Humorous",
                "Hungry",
                "Hurt",
                "Hushed",
                "Hypnotic",
                "Hysterical",
                "Icky",
                "Icy",
                "Ignorant",
                "Ill",
                "Illegal",
                "Illustrious",
                "Imaginary",
                "Immense",
                "Imminent",
                "Impartial",
                "Imperfect",
                "Impolite",
                "Important",
                "Incandescent",
                "Incompetent",
                "Industrious",
                "Incredible",
                "Inexpensive",
                "Infamous",
                "Innocent",
                "Inquisitive",
                "Insidious",
                "Instinctive",
                "Intelligent",
                "Interesting",
                "Invincible",
                "Irate",
                "Itchy",
                "Jaded",
                "Jagged",
                "Jealous",
                "Jolly",
                "Joyous",
                "Jumpy",
                "Juvenile",
                "Keen",
                "Kind",
                "Kindhearted",
                "Knowing",
                "Knowledgeable",
                "Known",
                "Labored",
                "Lame",
                "Large",
                "Last",
                "Late",
                "Laughable",
                "Lazy",
                "Lean",
                "Lethal",
                "Light",
                "Little",
                "Living",
                "Lonely",
                "Loud",
                "Lovely",
                "Lucky",
                "Magenta",
                "Magical",
                "Majestic",
                "Malicious",
                "Marked",
                "Massive",
                "Marvelous",
                "Mean",
                "Medical",
                "Melted",
                "Messy",
                "Mighty",
                "Military",
                "Mindless",
                "Minor",
                "Misty",
                "Mixed",
                "Modern",
                "Motionless",
                "Mysterious",
                "Naive",
                "Narrow",
                "Natural",
                "Neat",
                "Necessary",
                "Needless",
                "Needy",
                "Nervous",
                "New",
                "Nice",
                "Normal",
                "Nostalgic",
                "Numberless",
                "Obsolete",
                "Obtainable",
                "Oceanic",
                "Old-fashioned",
                "Omniscient",
                "Optimal",
                "Ordinary",
                "Organic",
                "Outstanding",
                "Oval",
                "Overrated",
                "Painful",
                "Parallel",
                "Pathetic",
                "Peaceful",
                "Penitent",
                "Perfect",
                "Periodic",
                "Petite",
                "Physical",
                "Pink",
                "Plastic",
                "Pleasant",
                "Pointless",
                "Polite",
                "Poor",
                "Precious",
                "Premium",
                "Present",
                "Pretty",
                "Private",
                "Productive",
                "Protective",
                "Public",
                "Puzzling",
                "Questionable",
                "Quick",
                "Quickest",
                "Rare",
                "Ready",
                "Real",
                "Rebel",
                "Regular",
                "Remarkable",
                "Responsible",
                "Romantic",
                "Round",
                "Royal",
                "Sad",
                "Safe",
                "Salty",
                "Satisfying",
                "Scared",
                "Scary",
                "Scientific",
                "Scrawny",
                "Screeching",
                "Second",
                "Second-hand",
                "Secret",
                "Selfish",
                "Sequacious",
                "Serious",
                "Shallow",
                "Sharp",
                "Shiny",
                "Shocking",
                "Short",
                "Shy",
                "Sick",
                "Silent",
                "Silky",
                "Silly",
                "Simple",
                "Skinny",
                "Slim",
                "Slimy",
                "Slippery",
                "Small",
                "Smart",
                "Smiling",
                "Smooth",
                "Sneaky",
                "Soft",
                "Solid",
                "Special",
                "Spectacular",
                "Spicy",
                "Spiky",
                "Splendid",
                "Spooky",
                "Spotless",
                "Square",
                "Staking",
                "Standing",
                "Steady",
                "Sticky",
                "Strange",
                "Striped",
                "Strong",
                "Successful",
                "Super",
                "Supreme",
                "Sweet",
                "Talented",
                "Tall",
                "Tasty",
                "Temporary",
                "Tense",
                "Terrible",
                "Terrific",
                "Tested",
                "Thankful",
                "Thick",
                "Thin",
                "Thirsty",
                "Thoughtful",
                "Tiny",
                "Tired",
                "Tricky",
                "Troubled",
                "True",
                "Ugly",
                "Ultra",
                "Unadvised",
                "Unarmed",
                "Uncovered",
                "Unhealthy",
                "Unique",
                "Unknown",
                "Unnatural",
                "Unused",
                "Unusual",
                "Used",
                "Useful",
                "Useless",
                "Valuable",
                "Violent",
                "Waiting",
                "Wandering",
                "Warm",
                "Weak",
                "Wealthy",
                "Whole",
                "Wise",
                "Wonderful",
                "Wooden",
                "Worried",
                "Worthless",
                "Wrong",
                "Menacing",
                "Trusting",
                "Unassuming",
                "Threatening"
        ), true);

        verbs = ConfigurationEngine.setList(file, fileConfiguration, "verbs", Arrays.asList(
                "Slashing",
                "Cutting",
                "Stabbing",
                "Scratching",
                "Killing",
                "Slaying",
                "Butchering",
                "Destroying",
                "Tickling",
                "Hugging",
                "Murdering",
                "Slapping",
                "Hissing",
                "Traveling",
                "Teleporting",
                "Blinking",
                "Destroying",
                "Wrecking",
                "Flashing",
                "Materializing",
                "Spawning",
                "Questioning",
                "Inquiring",
                "Pleading",
                "Demanding",
                "Interrogating",
                "Querying",
                "Assaulting",
                "Striking",
                "Ambushing",
                "Assailing",
                "Rushing",
                "Storming",
                "Bombarding",
                "Barraging",
                "Smiting",
                "Charging",
                "Clobbering",
                "Battling",
                "Battering",
                "Hammering",
                "Beating",
                "Combating",
                "Overwhelming",
                "Raiding",
                "Tackling",
                "Shooting",
                "Venturing",
                "Cracking",
                "Rupturing",
                "Smashing",
                "Shattering",
                "Fracturing",
                "Splintering",
                "Pulverizing",
                "Tearing",
                "Rending",
                "Snapping",
                "Bursting",
                "Exploding",
                "Damaging",
                "Fragmenting",
                "Splitting",
                "Fortifying",
                "Nudging",
                "Tapping",
                "Jostling",
                "Thumping",
                "Butting",
                "Clattering",
                "Striking",
                "Whacking",
                "Slamming",
                "Summoning",
                "Screaming",
                "Bellowing",
                "Roaring",
                "Shifting",
                "Transforming",
                "Modifying",
                "Twisting",
                "Mutating",
                "Distorting",
                "Blurring",
                "Adjusting",
                "Warping",
                "Altering",
                "Adapting",
                "Evolving",
                "Varying",
                "Hunting",
                "Trailing",
                "Following",
                "Stalking",
                "Shadowing",
                "Hounding",
                "Casing",
                "Mounting",
                "Ascending",
                "Rising",
                "Heaving",
                "Springing",
                "Cresting",
                "Gathering",
                "Corralling",
                "Hoarding",
                "Reaping",
                "Harvesting",
                "Saving",
                "Sheltering",
                "Cloaking",
                "Shrouding",
                "Enclosing",
                "Concealing",
                "Hiding",
                "Disguising",
                "Masking",
                "Burying",
                "Smothering",
                "Clouding",
                "Shielding",
                "Shading",
                "Sealing",
                "Enveloping",
                "Veiling",
                "Obscuring",
                "Traversing",
                "Fording",
                "Gliding",
                "Howling",
                "Whimpering",
                "Screaming",
                "Shrieking",
                "Squealing",
                "Roaring",
                "Wailing",
                "Bawling",
                "Screeching",
                "Cleaving",
                "Chopping",
                "Chipping",
                "Severing",
                "Slicing",
                "Snipping",
                "Splitting",
                "Axing",
                "Slashing",
                "Rending",
                "Tearing",
                "Thinning",
                "Cropping",
                "Carving",
                "Dissecting",
                "Hacking",
                "Piercing",
                "Sawing",
                "Shaving",
                "Shearing",
                "Mining",
                "Delving",
                "Excavating",
                "Burrowing",
                "Drilling",
                "Hollowing",
                "Gouging",
                "Tunneling",
                "Invading",
                "Boarding",
                "Wandering",
                "Infiltrating",
                "Intruding",
                "Evading",
                "Fleeing",
                "Running",
                "Dodging",
                "Crashing",
                "Battling",
                "Tussling",
                "Wrestling",
                "Scuffling",
                "Dueling",
                "Brawling",
                "Jousting",
                "Sparring",
                "Clashing",
                "Warring",
                "Grappling",
                "Scrapping",
                "Attacking",
                "Feuding",
                "Skirmishing",
                "Discovering",
                "Detecting",
                "Catching",
                "Solving",
                "Revealing",
                "Unearthing",
                "Leaping",
                "Bouncing",
                "Springing",
                "Vaulting",
                "Hopping",
                "Surging",
                "Punting",
                "Booting",
                "Dropkicking",
                "Sensing",
                "Perceiving",
                "Detecting",
                "Fading",
                "Bleeding",
                "Shrinking",
                "Weakening",
                "Abating",
                "Diminishing",
                "Forging",
                "Releasing",
                "Gathering",
                "Collecting",
                "Culling",
                "Crushing",
                "Propelling",
                "Jogging",
                "Sprinting",
                "Questing",
                "Scouting",
                "Exploring",
                "Digging",
                "Trembling",
                "Rattling",
                "Parting",
                "Hacking",
                "Rupturing",
                "Carving",
                "Dividing",
                "Halving",
                "Breaking",
                "Sundering",
                "Separating",
                "Rending",
                "Ripping",
                "Grazing",
                "Imprisoning",
                "Snaring",
                "Cornering",
                "Entangling",
                "Pinning",
                "Catching",
                "Restraining",
                "Binding",
                "Hooking",
                "Snagging",
                "Snatching",
                "Caging",
                "Capturing",
                "Haunting",
                "Creeping",
                "Sneaking",
                "Spying",
                "Avenging",
                "Storming"
        ), true);

        verbers = ConfigurationEngine.setList(file, fileConfiguration, "verb-ers (noun)", Arrays.asList(
                "World Breaker",
                "World Shatterer",
                "Avenger",
                "Ashbringer",
                "Windseeker",
                "Defiler",
                "Thunderfury",
                "Slicer",
                "Slasher",
                "Cutter",
                "Stabber",
                "Scratcher",
                "Killer",
                "Slayer",
                "Destroyer",
                "Hugger",
                "Murderer",
                "Slapper",
                "Traveller",
                "Teleporter",
                "Blinker",
                "Wrecker",
                "Materializer",
                "Spawner",
                "Demander",
                "Assaulter",
                "Striker",
                "Ambusher",
                "Rusher",
                "Stormer",
                "Bombarder",
                "Barrager",
                "Smiter",
                "Charger",
                "Battler",
                "Hammerer",
                "Beater",
                "Combater",
                "Overwhelmer",
                "Raider",
                "Tackler",
                "Shooter",
                "Venturer",
                "Cracker",
                "Smasher",
                "Shatterer",
                "Fracturer",
                "Splinterer",
                "Pulverizer",
                "Tearer",
                "Renderer",
                "Snapper",
                "Burster",
                "Exploder",
                "Damager",
                "Fragmenter",
                "Splitter",
                "Fortifier",
                "Nudger",
                "Tapper",
                "Thumper",
                "Butter",
                "Clatterer",
                "Striker",
                "Whacker",
                "Slammer",
                "Summoner",
                "Screamer",
                "Shifter",
                "Transformer",
                "Modifyer",
                "Twister",
                "Blurrer",
                "Warper",
                "Alterer",
                "Adapter",
                "Evolver",
                "HunterEnchantment",
                "Trailer",
                "Follower",
                "Stalker",
                "Shadower",
                "Hounder",
                "Caser",
                "Mounter",
                "Ascender",
                "Riser",
                "Springer",
                "Hoarder",
                "Reaper",
                "Harvester",
                "Saver",
                "Shelterer",
                "Cloaker",
                "Shrouder",
                "Encloser",
                "Hider",
                "Masker",
                "Buryer",
                "Clouder",
                "Shader",
                "Sealer",
                "Enveloper",
                "Veiler",
                "Traverser",
                "Forder",
                "Glider",
                "Howler",
                "Whimperer",
                "Screamer",
                "Squealer",
                "Bawler",
                "Screecher",
                "Chopper",
                "Chipper",
                "Snipper",
                "Splitter",
                "Axer",
                "Slasher",
                "Renderer",
                "Tearer",
                "Thinner",
                "Cropper",
                "Carver",
                "Hacker",
                "Piercer",
                "Sawer",
                "Shaver",
                "Shearer",
                "Miner",
                "Excavater",
                "Burrower",
                "Driller",
                "Tunneler",
                "Invader",
                "Boarder",
                "Wanderer",
                "Intruder",
                "Evader",
                "Runner",
                "Dodger",
                "Crasher",
                "Battler",
                "Wrestler",
                "Scuffler",
                "Dueler",
                "Brawler",
                "Clasher",
                "Grappler",
                "Scrapper",
                "Attacker",
                "Feuder",
                "Catcher",
                "Solver",
                "Revealer",
                "Leaper",
                "Bouncer",
                "Vaulter",
                "Hopper",
                "Surger",
                "Punter",
                "Dropkicker",
                "Perceiver",
                "Fader",
                "Bleeder",
                "Weakener",
                "Forger",
                "Releaser",
                "Gatherer",
                "Crusher",
                "Propeller",
                "Jogger",
                "Sprinter",
                "Scouter",
                "Explorer",
                "Digger",
                "Trembler",
                "Parter",
                "Hacker",
                "Carver",
                "Divider",
                "Halver",
                "Breaker",
                "Renderer",
                "Ripper",
                "Grazer",
                "Imprisoner",
                "Cornerer",
                "Pinner",
                "Catcher",
                "Restrainer",
                "Binder",
                "Snagger",
                "Snatcher",
                "Cager",
                "Capturer",
                "Haunter",
                "Creeper",
                "Sneaker",
                "Binder",
                "Jailer",
                "Seducer",
                "Dancer",
                "Blasphemer",
                "Eater",
                "Snorer",
                "Thruster",
                "Slapper"
        ), true);

        ConfigurationEngine.fileSaverCustomValues(fileConfiguration, file);

        MaterialGenerator.initializeValidProceduralMaterials();
    }

    private static void addMaterial(Material material) {
        ConfigurationEngine.setBoolean(fileConfiguration, "validMaterials." + material.name(), true);
    }

    public static void cacheMaterials() {
        validMaterials.clear();
        for (String material : fileConfiguration.getConfigurationSection("validMaterials").getKeys(false))
            if (fileConfiguration.getConfigurationSection("validMaterials").getBoolean(material))
                validMaterials.add(material);
    }


}
