package com.magmaguy.elitemobs.config.contentpackages.premade;

import com.magmaguy.elitemobs.config.contentpackages.ContentPackagesConfigFields;

import java.util.List;

public class HundredEventsPackage extends ContentPackagesConfigFields {
    public HundredEventsPackage() {
        super("hundred_events", true);
        setCustomEventFilenames(List.of(
                "undead_horde_event.yml",
                "creeperpede_event.yml",
                "monster_of_the_deep_event.yml",
                "werehare_event.yml",
                "bigfoot_event.yml",
                "wendigo_event.yml",
                "baba_rhoga_event.yml",
                "yezhi_baba_event.yml",
                "baba_yaga_event.yml",
                "tree_defender_event.yml",
                "yeti_event.yml",
                "rabbit_wolf_event.yml",
                "craftenmine_stacked_bones_event.yml",
                "craftenmine_terror_event.yml",
                "arachnid_matriarch_event.yml",
                "balloon_rider_event.yml",
                "fallen_knight_event.yml",
                "harmless_chicken_event.yml",
                "horrid_duplicator_event.yml",
                "living_shadow_event.yml",
                "greedy_dwarf_event.yml",
                "netherite_golem_event.yml",
                "night_crawler_event.yml",
                "evil_undead_event.yml",
                "foreign_visitor_event.yml",
                "goblin_army_event.yml",
                "nether_escapee_event.yml",
                "spider_knight_event.yml",
                "the_phantom_event.yml",
                "changeling_event.yml",
                "fox_king_cold_event.yml",
                "large_hopper_event.yml",
                "nightwing_event.yml",
                "super_mite_event.yml",
                "necromancer_event.yml",
                "wasp_queen_event.yml",
                "hog_rider_event.yml",
                "grunter_event.yml",
                "vex_top_event.yml",
                "moon_spider_event.yml",
                "regular_hoglin_event.yml",
                "okami_event.yml",
                "salty_corpse_event.yml",
                "pufferfish_event.yml",
                "water_pest_event.yml",
                "fulgora_event.yml",
                "krampus_event.yml",
                "merman_event.yml",
                "crone_event.yml",
                "fine_swine_event.yml",
                "gremlin_event.yml",
                "storm_caller_event.yml",
                "ender_guardian_event.yml",
                "sand_fiend_event.yml",
                "bone_skeleton_event.yml",
                "enders_event.yml",
                "earth_mite_event.yml",
                "exhumed_dead_event.yml",
                "moonlight_devourer_event.yml",
                "circus_ringmaster_event.yml",
                "suspicious_phantom_event.yml",
                "starving_hog_event.yml",
                "the_great_weaver_event.yml",
                "skeleton_knight_event.yml",
                "annoyed_drowned_event.yml",
                "enraged_snowman_event.yml",
                "fire_conjurer_event.yml",
                "undead_farmer_event.yml",
                "nether_bovine_event.yml",
                "sorcerer_supreme_event.yml",
                "animated_armor_event.yml",
                "beast_tamer_event.yml",
                "magma_construct_event.yml",
                "night_horder_event.yml",
                "bone_fiend_event.yml",
                "smallstack_event.yml",
                "cursed_bandit_event.yml",
                "rotting_diver_event.yml",
                "tree_trampler_event.yml",
                "firestarter_event.yml",
                "the_hunter_event.yml",
                "tiny_giant_event.yml",
                "morgana_event.yml",
                "sky_archer_event.yml",
                "warlock_event.yml",
                "jungle_lion_event.yml",
                "unwanted_visitor_event.yml",
                "bloated_jeffrey_event.yml",
                "banshee_event.yml",
                "endless_pursuer_event.yml",
                "mutated_mermaid_event.yml",
                "nether_hag_event.yml",
                "wandering_giant_event.yml",
                "divine_cinder_event.yml",
                "beach_bug_event.yml",
                "big_bad_wolf_event.yml",
                "nether_wasp_event.yml",
                "magi_giant_event.yml",
                "ancient_corpse_event.yml",
                "ender_lapin_event.yml"
        ));
        setName("&2100 Events");
        setCustomInfo(List.of("Expand your server with 100 new events!"));
        setDownloadLink("https://nightbreak.io/plugin/elitemobs/#100-events");
        setNightbreakSlug("events");
    }
}