package com.magmaguy.elitemobs.experimentalcombat.content;

import com.magmaguy.elitemobs.experimentalcombat.classes.AbilityDefinition;
import com.magmaguy.elitemobs.experimentalcombat.classes.AbilitySlot;
import com.magmaguy.elitemobs.experimentalcombat.classes.ClassBand;
import com.magmaguy.elitemobs.experimentalcombat.classes.ClassFormDefinition;
import com.magmaguy.elitemobs.experimentalcombat.classes.ClassResourceType;
import com.magmaguy.elitemobs.experimentalcombat.classes.FoundationSkillPair;
import com.magmaguy.elitemobs.experimentalcombat.classes.PassiveDefinition;
import com.magmaguy.elitemobs.experimentalcombat.classes.RootClassKit;
import com.magmaguy.elitemobs.skills.SkillType;

import java.util.List;
import java.util.Locale;

/** Player-facing form definitions consumed by the built-in content assembly. */
final class BuiltInClassDefinitions {

    private BuiltInClassDefinitions() {
    }

    static List<ClassFormDefinition> adventurerTree() {
        return List.of(new ClassFormDefinition("adventurer", "Adventurer", ClassBand.STARTER, null,
                new FoundationSkillPair(SkillType.ARMOR, SkillType.SWORDS),
                new RootClassKit(ClassResourceType.STAMINA,
                        ability("adventurer", AbilitySlot.MOBILITY, "Dodge", "Dash a short distance along your aim.")),
                ability("adventurer", AbilitySlot.SIGNATURE, "Quick Strike", "Strike one foe within melee reach."),
                ability("adventurer", AbilitySlot.UTILITY, "Second Wind", "Recover a little of your own health."),
                new PassiveDefinition("adventurer.passive", "Take 5% less damage. Practice with any weapon."),
                java.util.Arrays.stream(SkillType.values()).filter(skill -> skill != SkillType.ARMOR).toList()));
    }

    static List<ClassFormDefinition> paladinTree() {
        return List.of(
                root("paladin", "Paladin", SkillType.ARMOR, SkillType.SWORDS, ClassResourceType.RESOLVE,
                        "Divine Steed", "Ride an armored steed and taunt foes struck.",
                        "Provoke", "Taunt nearby foes and gain defense.",
                        "Repulse", "Blast nearby foes away.",
                        "Take less damage, but deal less.")
                        .withWeaponAffinities(SkillType.SWORDS, SkillType.MACES),

                form("guardian", "Guardian", ClassBand.LEVEL_31, "paladin", SkillType.ARMOR, SkillType.SPEARS,
                        "Intercession", "Redirect ally damage and taunt attackers.",
                        "Guardian Ring", "Shield allies and resist knockback.",
                        "Take less redirected damage, but move slower."),
                form("aegis", "Aegis", ClassBand.LEVEL_61, "guardian", SkillType.ARMOR, SkillType.SWORDS,
                        "Aegis Link", "Intercept attacks aimed at one ally.",
                        "Sanctuary Wall", "Shield allies and reduce damage in an area.",
                        "Boost links and shields, but move and hit slower."),
                form("bulwark", "Bulwark", ClassBand.LEVEL_91, "aegis", SkillType.ARMOR, SkillType.MACES,
                        "Hold the Line", "Root, taunt nearby foes and gain defense.",
                        "Unyielding Ground", "Shield allies from damage and control.",
                        "Gain defense while still, but lose it while moving."),
                form("shieldbearer", "Shieldbearer", ClassBand.LEVEL_91, "aegis", SkillType.ARMOR, SkillType.SWORDS,
                        "Manyfold Intercession", "Redirect damage from two allies.",
                        "Covering Wall", "Shield allies and grant defense and speed.",
                        "Guard more allies, but deal less damage."),
                form("justicar", "Justicar", ClassBand.LEVEL_61, "guardian", SkillType.ARMOR, SkillType.MACES,
                        "Judgment", "Store taunted damage, then strike back.",
                        "Censure", "Briefly weaken your attackers.",
                        "Hits empower retaliation but weaken self-healing."),
                form("templar", "Templar", ClassBand.LEVEL_91, "justicar", SkillType.ARMOR, SkillType.MACES,
                        "Consecrated Judgment", "Stored damage now hurts and heals.",
                        "Purging Bell", "Cleanse allies and briefly block debuffs.",
                        "Retaliation heals allies, but hits less hard."),
                form("inquisitor", "Inquisitor", ClassBand.LEVEL_91, "justicar", SkillType.SWORDS, SkillType.MACES,
                        "Final Sentence", "Strike elites harder as health falls.",
                        "Expose Heresy", "Reveal one foe and increase party damage.",
                        "Hurt lone elites more, but receive less healing."),

                form("warlord", "Warlord", ClassBand.LEVEL_31, "paladin", SkillType.SWORDS, SkillType.SPEARS,
                        "Commanding Shout", "Taunt foes and boost nearby allies.",
                        "Rally", "Cleanse slows and speed up allies.",
                        "Hit harder near allies, but lose some defense."),
                form("marshal", "Marshal", ClassBand.LEVEL_61, "warlord", SkillType.ARMOR, SkillType.SPEARS,
                        "Battle Standard", "Plant a banner that taunts and empowers.",
                        "Reform Ranks", "Grant allies speed and brief defense.",
                        "Boost grouped allies more, but gain less alone."),
                form("bannerlord", "Bannerlord", ClassBand.LEVEL_91, "marshal", SkillType.ARMOR, SkillType.SPEARS,
                        "Grand Standard", "Carry an aura that taunts and empowers.",
                        "Advance", "Speed allies while your aura lasts.",
                        "Your aura follows you, but you deal less damage."),
                form("strategist", "Strategist", ClassBand.LEVEL_91, "marshal", SkillType.SWORDS, SkillType.SPEARS,
                        "Perfect Formation", "Boost grouped damage and defense.",
                        "Fallback", "Shield allies and speed their retreat.",
                        "Recharge faster near allies, slower alone."),
                form("conqueror", "Conqueror", ClassBand.LEVEL_61, "warlord", SkillType.SWORDS, SkillType.AXES,
                        "Dominating Roar", "Pull, taunt and weaken nearby foes.",
                        "Press Forward", "Grant allies brief speed and power.",
                        "Hurt controlled foes more, but take more damage."),
                form("tyrant", "Tyrant", ClassBand.LEVEL_91, "conqueror", SkillType.AXES, SkillType.ARMOR,
                        "Kneel", "Frighten, turn and weaken nearby foes.",
                        "No Escape", "Reveal and heavily slow nearby foes.",
                        "Hurt controlled foes more, but others less."),
                form("champion", "Champion", ClassBand.LEVEL_91, "conqueror", SkillType.SWORDS, SkillType.AXES,
                        "Blade Dominion", "Cleave taunted foes and extend taunts.",
                        "Duel Order", "Knock back and taunt foes ahead.",
                        "Deal more damage, but lose Paladin defense.")
        );
    }

    static List<ClassFormDefinition> berserkerTree() {
        return List.of(
                root("berserker", "Berserker", SkillType.AXES, SkillType.MACES, ClassResourceType.FURY,
                        "Crater Leap", "Leap, then crush and stagger nearby foes.",
                        "Rampage", "Briefly gain damage and speed.",
                        "War Cry", "Briefly interrupt nearby foes.",
                        "Hit harder with more impact, but take more damage."),

                form("bloodrager", "Bloodrager", ClassBand.LEVEL_31, "berserker", SkillType.AXES, SkillType.MACES,
                        "Frenzy", "Gain damage and speed as health falls.",
                        "Blood Roar", "Cleanse slows and gain Fury.",
                        "Lost health boosts damage and damage taken."),
                form("reaver", "Reaver", ClassBand.LEVEL_61, "bloodrager", SkillType.AXES, SkillType.ARMOR,
                        "Blood Feast", "Briefly heal from damage dealt.",
                        "Scent Blood", "Reveal foes, gain speed and hunt the wounded.",
                        "Drain more at low health, but receive less healing."),
                form("bloodstorm", "Bloodstorm", ClassBand.LEVEL_91, "reaver", SkillType.AXES, SkillType.HOES,
                        "Crimson Cyclone", "Spin through groups, harm foes and heal.",
                        "Gore Trail", "Create a blood pool that heals you inside.",
                        "Heal more in groups, but hurt lone bosses less."),
                form("deathless", "Deathless", ClassBand.LEVEL_91, "reaver", SkillType.AXES, SkillType.ARMOR,
                        "Refuse Death", "Survive one fatal hit, heal and ward.",
                        "Defiant Roar", "Heal and gain heavy protection.",
                        "Survive once, but Refuse Death recovers slowly."),
                form("slayer", "Slayer", ClassBand.LEVEL_61, "bloodrager", SkillType.AXES, SkillType.SWORDS,
                        "Executioner's Rhythm", "Hit harder as target health falls.",
                        "Relentless Hunt", "Reveal nearby foes and gain pursuit speed.",
                        "Hurt wounded foes more, but lose defense."),
                form("headsman", "Headsman", ClassBand.LEVEL_91, "slayer", SkillType.AXES, SkillType.SWORDS,
                        "Final Stroke", "Deal extreme damage to a wounded target.",
                        "Condemn", "Mark a foe to deal more as its health falls.",
                        "Finish bosses well, but struggle with groups."),
                form("harvester", "Harvester", ClassBand.LEVEL_91, "slayer", SkillType.AXES, SkillType.HOES,
                        "Harvest Chain", "Chain through wounded foes and heal.",
                        "Reap the Weak", "Pull wounded foes into reach.",
                        "Chain group kills, but not against healthy bosses."),

                form("juggernaut", "Juggernaut", ClassBand.LEVEL_31, "berserker", SkillType.MACES, SkillType.ARMOR,
                        "Earthshatter", "Launch foes and weaken their attacks.",
                        "Unstoppable", "Resist slows, knockback and disruption.",
                        "Resist control and knockback, but move slower."),
                form("crusher", "Crusher", ClassBand.LEVEL_61, "juggernaut", SkillType.MACES, SkillType.AXES,
                        "Sunderquake", "Launch foes and weaken their attacks.",
                        "Fault Line", "Launch foes ahead.",
                        "Gain close damage and defense, but move slower."),
                form("siegebreaker", "Siegebreaker", ClassBand.LEVEL_91, "crusher", SkillType.MACES, SkillType.AXES,
                        "Ruinous Impact", "Smash groups and leave them weakened.",
                        "Breach", "Allies hurt foes more after you break defense.",
                        "Boost party damage, but lower direct damage."),
                form("titanbane", "Titanbane", ClassBand.LEVEL_91, "crusher", SkillType.MACES, SkillType.SPEARS,
                        "Giant Killer", "Strongly interrupt large foes and bosses.",
                        "Anchor Chain", "Stop one foe from fleeing or charging.",
                        "Control large foes, but struggle in groups."),
                form("dreadnought", "Dreadnought", ClassBand.LEVEL_61, "juggernaut", SkillType.MACES, SkillType.ARMOR,
                        "Seismic Chain", "Create expanding impacts around you.",
                        "Iron Roar", "Briefly ignore displacement and severe slows.",
                        "Resist control, but deal less critical damage."),
                form("warmonger", "Warmonger", ClassBand.LEVEL_91, "dreadnought", SkillType.AXES, SkillType.ARMOR,
                        "Panic Engine", "Damage, interrupt and frighten groups.",
                        "Challenge All", "Turn nearby foes and disrupt positions.",
                        "Disrupt groups, but hurt lone targets less."),
                form("colossus", "Colossus", ClassBand.LEVEL_91, "dreadnought", SkillType.MACES, SkillType.ARMOR,
                        "Worldbreaker", "Charge a devastating ground strike.",
                        "Immovable", "Gain huge defense while charging.",
                        "Charged hits devastate, but leave time to dodge.")
        );
    }

    static List<ClassFormDefinition> rangerTree() {
        return List.of(
                root("ranger", "Ranger", SkillType.BOWS, SkillType.CROSSBOWS, ClassResourceType.FOCUS,
                        "Windstep", "Dash without lowering your ranged weapon.",
                        "Volley", "Fire projectiles across an area.",
                        "Hunter's Mark", "Reveal nearby foes for 10% party damage.",
                        "Move faster until hit, then slow and hurt more."),

                form("sniper", "Sniper", ClassBand.LEVEL_31, "ranger", SkillType.BOWS, SkillType.CROSSBOWS,
                        "Aimed Shot", "Charge a powerful shot at a distant target.",
                        "Expose Weakness", "Apply a stronger Hunter's Mark.",
                        "Hurt distant foes more, but move slower."),
                form("bowmaster", "Bowmaster", ClassBand.LEVEL_61, "sniper", SkillType.BOWS, SkillType.SPEARS,
                        "Piercing Flight", "Shoot through every foe in a line.",
                        "Far Sight", "Mark foes from much farther away.",
                        "Keep range damage, but lose it up close."),
                form("deadeye", "Deadeye", ClassBand.LEVEL_91, "bowmaster", SkillType.BOWS, SkillType.CROSSBOWS,
                        "One Perfect Shot", "Fire a far shot with huge criticals.",
                        "Spotter's Mark", "Reveal one target to the party.",
                        "Criticals rise, but Perfect Shot recovers slower."),
                form("raincaller", "Raincaller", ClassBand.LEVEL_91, "bowmaster", SkillType.BOWS, SkillType.HOES,
                        "Arrow Storm", "Bombard an area with projectiles.",
                        "Storm Mark", "Reveal and weaken foes entering an area.",
                        "Cover areas well, but hurt lone foes less."),
                form("arbalist", "Arbalist", ClassBand.LEVEL_61, "sniper", SkillType.CROSSBOWS, SkillType.ARMOR,
                        "Breach Bolt", "Fire a heavy shot that weakens attacks.",
                        "Lock On", "Keep a target marked through speed or concealment.",
                        "Heavy shots hit harder, but you move slower."),
                form("artillerist", "Artillerist", ClassBand.LEVEL_91, "arbalist", SkillType.CROSSBOWS, SkillType.MACES,
                        "Repeater Burst", "Rapidly fire crossbow bolts.",
                        "Quickload Cache", "Gain speed, power and a burst of Focus.",
                        "Fire more bolts, but each hits less hard."),
                form("dragonslayer", "Dragonslayer", ClassBand.LEVEL_91, "arbalist", SkillType.CROSSBOWS, SkillType.SPEARS,
                        "Heartpiercer", "Pierce large elite foes with one shot.",
                        "Giant's Mark", "Mark a boss for more party damage.",
                        "Hurt bosses more, but ordinary foes less."),

                form("skirmisher", "Skirmisher", ClassBand.LEVEL_31, "ranger", SkillType.BOWS, SkillType.CROSSBOWS,
                        "Fan Volley", "Fire a wide spread while moving.",
                        "Running Hunt", "Reveal and weaken foes, then gain speed.",
                        "Movement boosts damage, but hits slow you more."),
                form("windrunner", "Windrunner", ClassBand.LEVEL_61, "skirmisher", SkillType.BOWS, SkillType.SPEARS,
                        "Strafe Volley", "Fire while moving and gain speed.",
                        "Tailwind", "Gain speed and restore Focus.",
                        "Hurt more while moving, less while still."),
                form("pathfinder", "Pathfinder", ClassBand.LEVEL_91, "windrunner", SkillType.BOWS, SkillType.SPEARS,
                        "Pack Hunt", "Attack a target and speed pursuers.",
                        "Guide's Trail", "Place a beacon that speeds nearby allies.",
                        "Boost party movement, but lower your damage."),
                form("tempest_archer", "Tempest Archer", ClassBand.LEVEL_91, "windrunner", SkillType.BOWS, SkillType.TRIDENTS,
                        "Cyclone Shot", "Chain an arc through nearby foes.",
                        "Gale Mark", "Reveal foes, gain speed and restore Focus.",
                        "Move for area damage, but hits weaken you."),
                form("saboteur", "Saboteur", ClassBand.LEVEL_61, "skirmisher", SkillType.CROSSBOWS, SkillType.HOES,
                        "Payload Bolt", "Plant a delayed explosive on one foe.",
                        "Snare Beacon", "Slow and reveal foes crossing its area.",
                        "Boost traps, but weaken direct projectiles."),
                form("trapper", "Trapper", ClassBand.LEVEL_91, "saboteur", SkillType.CROSSBOWS, SkillType.HOES,
                        "Kill Zone", "Deploy snares that repeatedly stop foes.",
                        "Tanglewire", "Extend your slows and movement limits.",
                        "Control movement better, but deal less burst damage."),
                form("demolitionist", "Demolitionist", ClassBand.LEVEL_91, "saboteur", SkillType.CROSSBOWS, SkillType.MACES,
                        "Cluster Bolt", "Scatter smaller blasts from one shot.",
                        "Blast Marker", "Make the next valid hit trigger a blast.",
                        "Boost blasts, but nearby combat hurts more.")
        );
    }

    static List<ClassFormDefinition> clericTree() {
        return List.of(
                root("cleric", "Cleric", SkillType.MACES, SkillType.TRIDENTS, ClassResourceType.GRACE,
                        "Guardian Flight", "Rush safely to an ally or Sanctuary.",
                        "Mend", "Heal an ally, or yourself for less.",
                        "Sanctuary", "Heal allies and anchor Guardian Flight.",
                        "Class healing rises, but attack damage falls."),

                form("priest", "Priest", ClassBand.LEVEL_31, "cleric", SkillType.ARMOR, SkillType.MACES,
                        "Prayer of Mending", "Heal the three weakest nearby allies.",
                        "Purify", "Cleanse one ally.",
                        "Heal more at once, but deal less attack damage."),
                form("hierophant", "Hierophant", ClassBand.LEVEL_61, "priest", SkillType.ARMOR, SkillType.MACES,
                        "Benediction", "Heal nearby allies heavily.",
                        "Sacred Silence", "Cleanse allies and interrupt nearby foes.",
                        "Heal groups better, but heal less alone."),
                form("saint", "Saint", ClassBand.LEVEL_91, "hierophant", SkillType.ARMOR, SkillType.TRIDENTS,
                        "Miracle", "Massively heal a dying ally.",
                        "Hallowed Ground", "Steadily heal allies in an area.",
                        "Rescue allies best, but hit weakly and recover slowly."),
                form("exorcist", "Exorcist", ClassBand.LEVEL_91, "hierophant", SkillType.MACES, SkillType.SWORDS,
                        "Smite and Succor", "Hurt a foe and heal the weakest ally.",
                        "Banish", "Knock foes away and weaken their damage.",
                        "Gain damage and control, but lose healing."),
                form("oracle", "Oracle", ClassBand.LEVEL_61, "priest", SkillType.TRIDENTS, SkillType.SPEARS,
                        "Foreseen Rescue", "Shield an ally, then heal when broken.",
                        "Foresight", "Briefly reduce damage to one ally.",
                        "Boost barriers, heals and defense; keep weak attacks."),
                form("fateweaver", "Fateweaver", ClassBand.LEVEL_91, "oracle", SkillType.TRIDENTS, SkillType.SPEARS,
                        "Rewrite Fate", "Block a fatal hit and heal that ally.",
                        "Prophecy", "Auto-protect an ally from the next major threat.",
                        "Prevent one death; Rewrite Fate recovers slowly."),
                form("seraph", "Seraph", ClassBand.LEVEL_91, "oracle", SkillType.ARMOR, SkillType.SPEARS,
                        "Chain of Mercy", "Chain healing through injured allies.",
                        "Ascension", "Shield and speed an ally; redirect some damage.",
                        "Heal and defend near allies; keep weak attacks."),

                form("shaman", "Shaman", ClassBand.LEVEL_31, "cleric", SkillType.HOES, SkillType.TRIDENTS,
                        "Life Current", "Tether and heal an ally until too far away.",
                        "Spirit Totem", "Repeatedly heal nearby allies.",
                        "Heal more over time, but lose rescue power."),
                form("lifewarden", "Lifewarden", ClassBand.LEVEL_61, "shaman", SkillType.HOES, SkillType.TRIDENTS,
                        "Renewing Bond", "Tether one ally for steady healing.",
                        "Sheltering Seed", "Delay a shield until heavy damage hits.",
                        "Heals last longer, but restore less at once."),
                form("grovekeeper", "Grovekeeper", ClassBand.LEVEL_91, "lifewarden", SkillType.HOES, SkillType.ARMOR,
                        "Verdant Bloom", "Continuously heal allies in an area.",
                        "Thorn Ward", "Shield an area and damage nearby foes.",
                        "Heal held ground, but lose power while moving."),
                form("shepherd", "Shepherd", ClassBand.LEVEL_91, "lifewarden", SkillType.HOES, SkillType.SPEARS,
                        "Guardian Chorus", "Heal more for each nearby ally.",
                        "Gather", "Grant allies speed and brief defense.",
                        "Heal groups better, but poorly alone."),
                form("spiritcaller", "Spiritcaller", ClassBand.LEVEL_61, "shaman", SkillType.HOES, SkillType.MACES,
                        "Ancestral Echo", "Repeat part of your next true heal.",
                        "Spirit Link", "Heal, shield and share damage across allies.",
                        "Echo healing and defense, but hits hurt more."),
                form("mistweaver", "Mistweaver", ClassBand.LEVEL_91, "spiritcaller", SkillType.HOES, SkillType.TRIDENTS,
                        "Restorative Tide", "Heal allies and harm nearby foes.",
                        "Veilstep", "Cleanse, speed and protect nearby allies.",
                        "Balance healing and damage, but master neither."),
                form("soulwarden", "Soulwarden", ClassBand.LEVEL_91, "spiritcaller", SkillType.HOES, SkillType.MACES,
                        "Ancestral Intervention", "Heal, shield and link allies.",
                        "Communion", "Heal, shield and share ally damage.",
                        "Protect groups, but rescue lone allies poorly.")
        );
    }

    static List<ClassFormDefinition> spellcasterTree() {
        return List.of(
                root("spellcaster", "Spellcaster", SkillType.STAVES, SkillType.WANDS, ClassResourceType.MANA,
                        "Blink", "Blink a short distance along a safe, clear path.",
                        "Arcane Bolt", "Fire a focused bolt at your target.",
                        "Mana Ward", "Spend Mana for a temporary shield.",
                        "Boost damage and recovery, but take more damage."),

                form("mage", "Mage", ClassBand.LEVEL_31, "spellcaster", SkillType.STAVES, SkillType.WANDS,
                        "Arcane Volley", "Fire bolts through foes ahead.",
                        "Spell Echo", "Briefly boost your damage.",
                        "Boost spell damage, but lose physical defense."),
                form("elementalist", "Elementalist", ClassBand.LEVEL_61, "mage", SkillType.STAVES, SkillType.WANDS,
                        "Elemental Convergence", "Damage and disrupt a target area.",
                        "Elemental Exposure", "Reveal foes for more party damage.",
                        "Boost area damage, but nearby foes hurt more."),
                form("pyromancer", "Pyromancer", ClassBand.LEVEL_91, "elementalist", SkillType.STAVES, SkillType.WANDS,
                        "Inferno", "Burn an area with repeated heavy damage.",
                        "Flashover", "Mark foes to take more damage briefly.",
                        "Deal far more spell damage, but take more damage."),
                form("cryomancer", "Cryomancer", ClassBand.LEVEL_91, "elementalist", SkillType.STAVES, SkillType.WANDS,
                        "Whiteout", "Repeatedly damage and slow foes in a storm.",
                        "Ice Barrier", "Cleanse and gain a strong shield.",
                        "Gain defense and recovery, but lose spell damage."),
                form("battlemage", "Battlemage", ClassBand.LEVEL_61, "mage", SkillType.STAVES, SkillType.WANDS,
                        "Arcane Cleave", "Sweep foes and strengthen your ward.",
                        "Runic Guard", "Reduce incoming damage with runes.",
                        "Take less damage up close, but move slower."),
                form("spellblade", "Spellblade", ClassBand.LEVEL_91, "battlemage", SkillType.STAVES, SkillType.WANDS,
                        "Aether Blade", "Cut through foes ahead with fast magic.",
                        "Warcasting", "Briefly gain speed, power and a shield.",
                        "Gain damage and speed, but lose defense."),
                form("arcane_knight", "Arcane Knight", ClassBand.LEVEL_91, "battlemage", SkillType.STAVES, SkillType.WANDS,
                        "Spellbreaker", "Damage foes and weaken their attacks.",
                        "Aegis Pulse", "Shield allies and reduce incoming damage.",
                        "Gain defense and recovery, but lose damage."),

                form("occultist", "Occultist", ClassBand.LEVEL_31, "spellcaster", SkillType.STAVES, SkillType.WANDS,
                        "Umbral Lance", "Pierce and weaken one foe.",
                        "Occult Sight", "Reveal foes for more party damage.",
                        "Recover attacks faster, but heal less."),
                form("necromancer", "Necromancer", ClassBand.LEVEL_61, "occultist", SkillType.STAVES, SkillType.WANDS,
                        "Soul Drain", "Raise an undead servant from an Elite corpse.",
                        "Grave Chill", "Slow and weaken nearby foes.",
                        "Drain more health, but move slower."),
                form("lich", "Lich", ClassBand.LEVEL_91, "necromancer", SkillType.STAVES, SkillType.WANDS,
                        "Death Coil", "Raise an undead that drains and weakens foes.",
                        "Phylactery Ward", "Block one fatal hit while warded.",
                        "Deal and heal more, but ward breaks hurt more."),
                form("plaguebringer", "Plaguebringer", ClassBand.LEVEL_91, "necromancer", SkillType.STAVES, SkillType.WANDS,
                        "Rotting Ground", "Raise an undead servant that spreads rot.",
                        "Miasma", "Slow and weaken nearby foes.",
                        "Hit harder, recover faster, but move slower."),
                form("summoner", "Summoner", ClassBand.LEVEL_61, "occultist", SkillType.STAVES, SkillType.WANDS,
                        "Arcane Servitor", "Call an animal servant to defend you.",
                        "Commanding Sigil", "Empower and shield nearby allies.",
                        "Gain recovery and defense, but weaken direct magic."),
                form("demonologist", "Demonologist", ClassBand.LEVEL_91, "summoner", SkillType.STAVES, SkillType.WANDS,
                        "Abyssal Gate", "Open a portal that calls a Nether servant.",
                        "Pact of Ruin", "Trade defense for spell damage and a shield.",
                        "Deal and take far more damage."),
                form("spiritbinder", "Spiritbinder", ClassBand.LEVEL_91, "summoner", SkillType.STAVES, SkillType.WANDS,
                        "Guardian Eidolon", "Call a protective Vex servant.",
                        "Shared Essence", "Shield allies and spread incoming damage.",
                        "Boost heals and recovery; weaken direct spells.")
        );
    }

    private static ClassFormDefinition root(
            String id,
            String displayName,
            SkillType firstSkill,
            SkillType secondSkill,
            ClassResourceType resourceType,
            String mobilityName,
            String mobilityDescription,
            String signatureName,
            String signatureDescription,
            String utilityName,
            String utilityDescription,
            String passiveDescription) {
        return ClassFormDefinition.root(
                id,
                displayName,
                new FoundationSkillPair(firstSkill, secondSkill),
                new RootClassKit(resourceType, ability(id, AbilitySlot.MOBILITY, mobilityName, mobilityDescription)),
                ability(id, AbilitySlot.SIGNATURE, signatureName, signatureDescription),
                ability(id, AbilitySlot.UTILITY, utilityName, utilityDescription),
                new PassiveDefinition(id + ".passive", passiveDescription)).afterStarter("adventurer");
    }

    private static ClassFormDefinition form(
            String id,
            String displayName,
            ClassBand band,
            String parentId,
            SkillType firstSkill,
            SkillType secondSkill,
            String signatureName,
            String signatureDescription,
            String utilityName,
            String utilityDescription,
            String passiveDescription) {
        return ClassFormDefinition.specialization(
                id,
                displayName,
                band,
                parentId,
                new FoundationSkillPair(firstSkill, secondSkill),
                ability(id, AbilitySlot.SIGNATURE, signatureName, signatureDescription),
                ability(id, AbilitySlot.UTILITY, utilityName, utilityDescription),
                new PassiveDefinition(id + ".passive", passiveDescription));
    }

    private static AbilityDefinition ability(
            String formId,
            AbilitySlot slot,
            String displayName,
            String description) {
        return new AbilityDefinition(
                formId + "." + slot.name().toLowerCase(Locale.ROOT),
                displayName,
                slot,
                description);
    }

}
