package com.magmaguy.elitemobs.powers.scripts.enums;

public enum TargetType {
    NEARBY_PLAYERS,
    NEARBY_MOBS,
    WORLD_PLAYERS,
    ALL_PLAYERS,
    DIRECT_TARGET,
    SELF,
    SELF_SPAWN,
    LOCATION,
    LOCATIONS,
    ZONE_FULL,
    ZONE_BORDER,
    LANDING_LOCATION,
    ACTION_TARGET,
    INHERIT_SCRIPT_TARGET,
    INHERIT_SCRIPT_ZONE_FULL,
    INHERIT_SCRIPT_ZONE_BORDER
}
